# Penanganan Kesalahan

## Penggunaan *error*

Saat terjadi kesalahan, Go menyediakan fasilitas pada pustaka standar `errors`. Berikut adalah
contohnya:

```go
package main

import "fmt"
import "errors"

func bagi(angka1, angka2 float64) (float64, error) {
	if angka2 == 0 {
		return -1, errors.New("Pembagian dengan angka 0 dilarang")
	}
	return angka1 / angka2, nil
}

func main() {

	var hasilBagi, err = bagi(23, 3)
	fmt.Println(hasilBagi, err)

	var hasilBagi2, err2 = bagi(23, 0)
	fmt.Println(hasilBagi2, err2)

}
```

Hasilnya:

```bash
$ go run error.go
7.666666666666667 <nil>
-1 Pembagian dengan angka 0 dilarang
$ 
```

## Panic dan Recover 

Go menyediakan konstruksi *panic* dan *recover* untuk menangani kesalahan yang tidak bisa "ditolerir". Sebagai contoh, jika aplikasi kita mutlak memerlukan suatu file konfigurasi dan file konfigurasi tersebut tidak ada, maka kita bisa menggunakan *panic* untuk menghentikan eksekusi aplikasi dan kemudian memberikan pesan kesalahan. Jika kita hanya menggunakan *panic*, maka program akan berakhir dengan pesan error serta dump dari instruksi biner yang menyebabkan error tersebut. Hal ini seringkali tidak dikehendaki sehingga diperlukan *recover* untuk mengakhiri program dengan baik.

```go
// slightly modified from:
// https://blog.golang.org/defer-panic-and-recover
package main

import "fmt"

func main() {
	f()
	f2()
	fmt.Println("Returned normally from f.")
}

func f() {

	// jika ada panic, maka defer akan dipanggil
	defer func() {
		// mengambil nilai revocer, jika tidak nil (karena panic)
		// maka pada bagian ini akan dilakukan berbagai hal untuk
		// menangani panic tersebut
		if r := recover(); r != nil {
			fmt.Println("Recovered in f", r)
		}
	}()
	fmt.Println("Calling g.")
	g(0)
	fmt.Println("Returned normally from g.")

}

func f2() {

	fmt.Println("Calling g.")
	g(0)
	fmt.Println("Will not be executed because of panic")

}

func g(i int) {
	if i > 3 {
		fmt.Println("Panicking!")
		panic(fmt.Sprintf("%v", i))
	}
	defer fmt.Println("Defer in g", i)
	fmt.Println("Printing in g", i)
	// rekursif
	g(i + 1)
}
```

Hasilnya:

```bash
$ go run panic-recover.go
Calling g.
Printing in g 0
Printing in g 1
Printing in g 2
Printing in g 3
Panicking!
Defer in g 3
Defer in g 2
Defer in g 1
Defer in g 0
Recovered in f 4
Calling g.
Printing in g 0
Printing in g 1
Printing in g 2
Printing in g 3
Panicking!
Defer in g 3
Defer in g 2
Defer in g 1
Defer in g 0
panic: 4

goroutine 1 [running]:
main.g(0x4)
	/home/bpdp/kerjaan/git-repos/oldstager/current/github/oldstager/buku-go/src/bab-07/panic-recover.go:41 +0x28a
main.g(0x3)
	/home/bpdp/kerjaan/git-repos/oldstager/current/github/oldstager/buku-go/src/bab-07/panic-recover.go:46 +0x16f
main.g(0x2)
	/home/bpdp/kerjaan/git-repos/oldstager/current/github/oldstager/buku-go/src/bab-07/panic-recover.go:46 +0x16f
main.g(0x1)
	/home/bpdp/kerjaan/git-repos/oldstager/current/github/oldstager/buku-go/src/bab-07/panic-recover.go:46 +0x16f
main.g(0x0)
	/home/bpdp/kerjaan/git-repos/oldstager/current/github/oldstager/buku-go/src/bab-07/panic-recover.go:46 +0x16f
main.f2()
	/home/bpdp/kerjaan/git-repos/oldstager/current/github/oldstager/buku-go/src/bab-07/panic-recover.go:33 +0x87
main.main()
	/home/bpdp/kerjaan/git-repos/oldstager/current/github/oldstager/buku-go/src/bab-07/panic-recover.go:9 +0x27
exit status 2
$
```
